### ISSUE TITLE
More than 'id'

### ISSUE THREAD

**Issue by mdsumner** [yutannihilation/string2path#2]
I hope it's possible to get more grouping identifiers for multipolygons and holes. Sorry this is cursory, just worried I might forget to ask again. . I can follow up with more explanation, but ideal would be 'linestring_id', 'polygon_id', and 'multipolygon_id' as per sfheaders.

**Comment by yutannihilation** [comment]
Thanks for the suggestion, but I'm afraid polygon_id and multipolygon_id are difficult to implement. I'm not sure if I understand this correctly, but I feel there's no such a concept as "holed polygon" either in font representation or in the lyon's fill representation. There's only strokes in the former, and holes and polygons in the latter.

c.f. https://www.w3.org/TR/SVG/painting.html#FillRuleProperty

**Comment by mdsumner** [comment]
Ok thanks, I'll explore - can do intersection tests if nothing else
