### ISSUE TITLE
Using NotoColorEmoji.ttf and smiley doesn't work, but using EmojiOne.ttf does

### ISSUE THREAD

**Issue by mskyttner** [yutannihilation/string2path#24]
Thanks for awesome package! 

I noticed that using NotoColorEmoji.ttf gives blank results while EmojiOne.ttf from `emojifont` R package works.

```r
# install.packages("emojifont")
ttf_emojione <- dir(system.file("emoji_fonts", package = "emojifont"), full.names = TRUE)[1]
ttf_noto <- systemfonts::system_fonts() %>% filter(grepl("NotoColorEmoji", name)) %>% pull(path)

ttf <- ttf_noto
#ttf <- ttf_emojione

d <-
  string2path::string2path("😄", ttf, tolerance = 1e-4) %>%
  tibble::rowid_to_column()

ggplot(d) +
  geom_path(aes(x, y, group = path_id, colour = factor(glyph_id)), size = 1.5) +
  theme_void() +
  coord_equal() +
  theme(legend.position = "none") +
  scale_colour_viridis_d(option = "H")
```

What am I missing?

**Comment by yutannihilation** [comment]
That's because the underlying crate doesn't support color emoji fonts (yet?).

https://github.com/RazrFalcon/ttf-parser/issues/69

**Comment by mskyttner** [comment]
Ah that explains it! 

BTW - I understand that raster fonts are probably not in scope for this package - but for raster to vector conversion the [vtracer crate](https://crates.io/crates/vtracer) with source at https://github.com/visioncortex/vtracer appears to deal with colors better than for example the classical potrace library. It would be nice with an R package capable of doing raster-to-vector conversion like that.

**Comment by yutannihilation** [comment]
Looks nice, thanks for the information! But, yes, it's out of scope of this package :)
